services:
#    front_end.example:
#        class: FrontEndBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    front_end.service.hello_service:
        class: FrontEndBundle\Service\HelloService
